export default {
  SET_USERDATA: 'SET_USERDATA',
  SET_HEADLINE: 'SET_HEADLINE',
  SET_ACTIVITIES: 'SET_ACTIVITIES',
  SET_SUPER_SALE: 'SET_SUPER_SALE',
  SET_SHOPS: 'SET_SHOPS',
  SET_SEARCH_VAL: 'SET_SEARCH_VAL',
}
